import { NextPage } from "next";
import Head from "next/head";
import Navbar from "~/components/Navbar/Navba";
import SearchInput from "~/components/SearchInput/SearchInput";
import { useSession } from "next-auth/react";

const HomePage: NextPage = () => {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      {sessionData ? (
        <div className="flex flex-col items-center gap-2">
          {/* Your content goes here */}
          <SearchInput />
        </div>
      ) : (
        <div role="alert">
          <div className="rounded-t bg-red-500 px-4 py-2 font-bold text-white">
            Uknwon User
          </div>
          <div className="rounded-b border border-t-0 border-red-400 bg-red-100 px-4 py-3 text-red-700">
            <p>Please first Sign in, to access to the content</p>
          </div>
        </div>
      )}
      </main>
    </>
  );
};

export default HomePage;