import { NextPage } from "next";
import Head from "next/head";
import Navbar from "~/components/Navbar/Navba";
import Content from "./index/Content";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Content />
      </main>
    </>
  );
};

export default HomePage;